### ISSUE TITLE
[기능] 투표의 유효 여부를 확인할 수 있는 API 

### ISSUE THREAD

**Issue by hee000** [WooSeob/baemin-mate#30]
## 세부 내용

이미 투표를 했거나, 종료된 투표인 경우 투표가 불가능함을 알려주는 api

## 진행 현황
 - [ ] todo 1
 - [ ] todo 2
 - [ ] todo 3

**Comment by WooSeob** [comment]
## API 명세
### Endpoint

```html
GET room/{roomId}/vote/{voteId}
```

### Response

| 이름       | 타입    | 설명                                                         | 제약 조건 | 필수 여부 |
| ---------- | ------- | ------------------------------------------------------------ | --------- | --------- |
| id         | string  | 투표 id                                                      |           | O         |
| type       | integer | 투표 타입 (강퇴 투표 = 0, 리셋 투표 = 1)                     |           | O         |
| finished   | boolean | 투표 종료 여부                                               |           | O         |
| result     | boolean | 투표 결과                                                    |           | O         |
| metadataId | string  | 메타 데이터 id (강퇴 투표의 경우 강퇴 대상 유저 id)          |           | O         |
| canVote    | boolean | 의견 제출 대상자 여부                                        |           | O         |
| submitted  | boolean | 의견 제출 여부 (해당 속성이 false 라고 하더라도 canVote = false 인 경우에는 의견을 제출할 수 없음) |           | O         |
