### ISSUE TITLE
/notification 응답

### ISSUE THREAD

**Issue by hee000** [WooSeob/baemin-mate#36]
> 반드시 `Labels` 에서 Rest API 혹은 Socket 중 해당되는것을 선택해 주세요.
## 해당 API
```html
[HTTP METHOD] [URI]
```
or
```html
[SOCKET NAME SPACE] [EVENT NAME]
```

## 변경 내용
요청하고자 하는 변경사항에 대해 기술해 주세요. http method 혹은 uri, name space 혹은 event name, 또는 request or response

patch /notification 에 대한 응답 요구

## 사유

알림 온오프를 위해 rest 요청에 대한 응답이 필요함.

enabled: false 인 경우 200으로 오지만,
enabled: true 인 경우 아무런 응답이 오지않음.

**Comment by WooSeob** [comment]
클라이언트측에서 요청이 누락된것으로 확인
