### ISSUE TITLE
[버그] socket /match의 new-arrive emit 이벤트

### ISSUE THREAD

**Issue by hee000** [WooSeob/baemin-mate#38]
## 발생 상황

emit 이벤트 중 new-arrive의 값 createdAt이 null 값으로 옴.

## 에러 로그

    createdAt = "<null>";
    id = "f15209f9-6ad8-442a-8ea0-179b96f79941";
    priceAtLeast = 88;
    purchaserName = "\Uc870\Ucc3d\Ud76c";
    section = "\Ube44\Ubd09\Uad00";
    shopName = "\U3139\U314e";
    total = 0;

**Comment by WooSeob** [comment]
save() 사용 시 CreateDateColumn 데코레이터를 사용한 컬럼인 createdAt 컬럼이 세팅되지 않아서 생긴 문제로 일단 해당 엔티티를 저장후 find해서 해결
